apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-webapp
  name: python-webapp-deployment
spec:
  externalIPs:
  - 172.31.0.100
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8081
    nodePort: 31007
  selector:
    app: python-webapp
  type: LoadBalancer
status:
  loadBalancer: {}
